// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIWUmwsBiE-ZyrjTdcsjVnxdCnAkGegAs',
    appId: '1:257670114620:web:8e991e6f08946277058239',
    messagingSenderId: '257670114620',
    projectId: 'hostel-finder-46d54',
    authDomain: 'hostel-finder-46d54.firebaseapp.com',
    storageBucket: 'hostel-finder-46d54.appspot.com',
    measurementId: 'G-11WZ5PWM17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe2kH9EOpkRB42xVV2xPfZRbCZWdu3eMw',
    appId: '1:257670114620:android:04435ea76eb3aa17058239',
    messagingSenderId: '257670114620',
    projectId: 'hostel-finder-46d54',
    storageBucket: 'hostel-finder-46d54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdZCkxd2EVZYqvtQLxfe_BJSqReyRVwCo',
    appId: '1:257670114620:ios:7d1770ec33fe6407058239',
    messagingSenderId: '257670114620',
    projectId: 'hostel-finder-46d54',
    storageBucket: 'hostel-finder-46d54.appspot.com',
    iosBundleId: 'com.example.hostelFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdZCkxd2EVZYqvtQLxfe_BJSqReyRVwCo',
    appId: '1:257670114620:ios:7baa06f9adfb19b2058239',
    messagingSenderId: '257670114620',
    projectId: 'hostel-finder-46d54',
    storageBucket: 'hostel-finder-46d54.appspot.com',
    iosBundleId: 'com.example.hostelFinder.RunnerTests',
  );
}
